name: DeepSeek Auto Agent

on:
  workflow_dispatch:

jobs:
  run-deepseek:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run DeepSeek Agent
        uses: deepseek-ai/agent-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          entry_point: "src/"
          instructions: |
            ๐ฏ ุงูููุงู:
            - ุฃูุดุฆ ูููุงุช ูุงุฌูุฉ ูุณุชุฎุฏู ููุฃุทูุงู ุฏุงุฎู ูุฌูุฏ `src/frontend/`
            - ุงุณุชุฎุฏู HTML + TailwindCSS ุฃู Bootstrap
            - ุฃุถู ุตูุญุฉ ุฑุฆูุณูุฉ ูููุง: ุดุนุงุฑ ุงููุดุฑูุนุ ูุตู ูุตูุฑุ ุฒุฑ ุฏุฎููุ ุฒุฑ ุชุณุฌูู
            - ูุง ุชุฎุฑุฌ ูู ูุฌูุฏ `src/`ุ ูุถุน ูู ุงูุฃููุงุฏ ุจุฏุงุฎูู ููุท.
            - ูุง ุชูุฑุฑ ุงููููุงุชุ ูุญุงูุธ ุนูู ุชูุณูู ูุธูู

            โ ุจุนุฏ ุชูููุฐ ุงููููุฉ:
            - ูู ุจุฅูุดุงุก Pull Request ุชููุงุฆููุง ูููุฑุงุฌุนุฉ

